import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { fareForLeg } from '../router/fare.ts'
import { PACK_HEADERS, packFromCsv, type PackFile } from './packFromCsv.ts'

// Generated by scripts/rail-fares-to-csv.mjs from the transcribed official matrices.
const dir = 'data/metro-manila/rail-pack'
const files = Object.fromEntries(Object.keys(PACK_HEADERS).map((f) => [f, readFileSync(`${dir}/${f}.csv`, 'utf8')])) as Record<PackFile, string>
const { pack, issues } = packFromCsv(files, { id: 'rail-fares' })
const fare = (id: string) => pack.fares.find((f) => f.id === id)!
const AS_OF = '2026-10-10'

describe('rail fare pack', () => {
  it('has no schema or reference errors', () => {
    expect(issues.filter((i) => i.level === 'error')).toEqual([])
  })

  it('matches the transcribed grids', () => {
    expect(fareForLeg('rail-lrt1-dr_santos', 'rail-lrt1-ninoy_aquino', 0, fare('lrt1-single-journey-2025-04-02'), AS_OF)?.centavos).toBe(2000)
    expect(fareForLeg('rail-lrt1-ninoy_aquino', 'rail-lrt1-dr_santos', 0, fare('lrt1-single-journey-2025-04-02'), AS_OF)?.centavos).toBe(2000)
    const mrt = fareForLeg('rail-mrt3-north_avenue', 'rail-mrt3-quezon_avenue', 0, fare('mrt3-regular-current-posted'), AS_OF)!
    expect(mrt.scheduledCentavos).toBe(1300)
    expect(mrt.centavos).toBe(600) // 50% all-passenger promotion since 2026-03-23, 13 -> 6 per the charter
  })

  it('applies the LRT-2 50% promotion only inside its window', () => {
    const f = fare('lrt2-sjt-scheduled-2023')
    const after = fareForLeg('rail-lrt2-recto', 'rail-lrt2-legarda', 0, f, AS_OF)!
    const before = fareForLeg('rail-lrt2-recto', 'rail-lrt2-legarda', 0, f, '2026-03-01')!
    expect(before.centavos).toBe(1500)
    expect(after.scheduledCentavos).toBe(1500)
    expect(after.centavos).toBeLessThan(1500)
    expect(after.promotion?.id).toBe('lrt2-sjt-discounted-2026')
  })

  it('returns null for an unknown pair, never an estimate', () => {
    expect(fareForLeg('rail-lrt1-dr_santos', 'rail-lrt2-recto', 0, fare('lrt1-single-journey-2025-04-02'), AS_OF)).toBeNull()
  })
})
