// Usage: npm run build && npm run audit
// Writes docs/audit.md: Lighthouse scores for the production build, bundle and
// precache sizes, and an accessibility sweep of every screen (tap target size,
// accessible names, text at 200%, reduced motion, focus order).
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { gzipSync } from 'node:zlib'
import lighthouse from 'lighthouse'
import puppeteer from 'puppeteer-core'
import { preview } from 'vite'
import { findChrome } from './lib/browser.mjs'

const PORT = 4178
const BASE = `http://localhost:${PORT}/`
const DEBUG_PORT = 9333

if (!existsSync('dist/sw.js')) {
  console.error('dist/sw.js not found. Run "npm run build" first.')
  process.exit(1)
}

const server = await preview({ preview: { port: PORT, strictPort: true }, logLevel: 'silent' })
const browser = await puppeteer.launch({
  executablePath: findChrome(),
  headless: true,
  args: [`--remote-debugging-port=${DEBUG_PORT}`],
})

const lines = ['# Audit', '', 'Generated by `npm run audit` against the production build. Do not edit by hand.', '']

// --- Sizes -------------------------------------------------------------------

const precached = [...readFileSync('dist/sw.js', 'utf8').matchAll(/url:"([^"]+)"/g)].map((match) => {
  const file = join('dist', match[1])
  const raw = readFileSync(file)
  return { url: match[1], size: statSync(file).size, gzip: gzipSync(raw).length }
})
const kib = (bytes) => `${(bytes / 1024).toFixed(0)} KiB`
const sum = (list, key) => list.reduce((total, entry) => total + entry[key], 0)
const runtime = precached.filter((entry) => entry.url.endsWith('.js') && entry.size > 2 * 1024 * 1024)
const shell = precached.filter((entry) => !runtime.includes(entry))
const mascot = existsSync('dist/mascot')
  ? readdirSync('dist/mascot').reduce((total, file) => total + statSync(join('dist/mascot', file)).size, 0)
  : 0

lines.push('## Sizes', '')
lines.push('| What | Files | Size | Gzipped |', '|---|---|---|---|')
lines.push(`| App shell precache (everything except the AI runtime) | ${shell.length} | ${kib(sum(shell, 'size'))} | ${kib(sum(shell, 'gzip'))} |`)
lines.push(`| AI runtime chunk (WebLLM, lazy, precached for offline) | ${runtime.length} | ${kib(sum(runtime, 'size'))} | ${kib(sum(runtime, 'gzip'))} |`)
lines.push(`| Whole precache | ${precached.length} | ${kib(sum(precached, 'size'))} | ${kib(sum(precached, 'gzip'))} |`)
lines.push(`| Mascot images (inside the shell) | | ${kib(mascot)} | |`)
lines.push('', 'The AI model itself is not in the precache. It is downloaded once from the Setup screen (277 MB to 926 MB depending on the model; see `docs/model-benchmark.md`).', '')

// --- Lighthouse ----------------------------------------------------------------

console.log('Lighthouse (mobile, simulated slow 4G and 4x CPU slowdown)…')
const run = await lighthouse(BASE, {
  port: DEBUG_PORT,
  output: 'json',
  logLevel: 'error',
  onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo'],
})
const lhr = run.lhr
const score = (id) => (lhr.categories[id]?.score === null ? 'n/a' : Math.round(lhr.categories[id].score * 100))
const metric = (id) => lhr.audits[id]?.displayValue ?? 'n/a'

lines.push('## Lighthouse', '')
lines.push(`Lighthouse ${lhr.lighthouseVersion}, mobile emulation, simulated slow 4G with 4x CPU slowdown, first load of \`/\` with an empty cache.`, '')
lines.push('| Category | Score |', '|---|---|')
for (const id of ['performance', 'accessibility', 'best-practices', 'seo']) lines.push(`| ${lhr.categories[id].title} | ${score(id)} |`)
lines.push('', 'Lighthouse removed its PWA category in version 12, so installability and offline behaviour are covered by `npm run check:offline` and `npm run test:e2e` instead.', '')
lines.push('| Metric (throttled) | Value |', '|---|---|')
for (const [id, label] of [
  ['first-contentful-paint', 'First Contentful Paint'],
  ['largest-contentful-paint', 'Largest Contentful Paint'],
  ['interactive', 'Time to Interactive'],
  ['total-blocking-time', 'Total Blocking Time'],
  ['cumulative-layout-shift', 'Cumulative Layout Shift'],
  ['speed-index', 'Speed Index'],
]) lines.push(`| ${label} | ${metric(id)} |`)
const transfer = lhr.audits['total-byte-weight']?.numericValue
const requests = lhr.audits['network-requests']?.details?.items ?? []
lines.push(`| First-load page transfer, as Lighthouse counts it | ${transfer ? kib(transfer) : 'n/a'} in ${requests.length} requests |`)
lines.push(`| Background precache by the service worker after first load (not in the line above) | ${kib(sum(precached, 'gzip'))} gzipped, ${kib(sum(precached, 'size'))} on disk |`)
const thirdParty = requests.filter((item) => !item.url.startsWith(BASE))
lines.push(`| Requests to other origins on first load | ${thirdParty.length} |`, '')

const failed = Object.values(lhr.categories)
  .flatMap((category) => category.auditRefs.map((ref) => ({ category: category.title, audit: lhr.audits[ref.id], weight: ref.weight })))
  .filter(({ audit, weight }) => audit.score !== null && audit.score < 0.9 && weight > 0 && audit.scoreDisplayMode !== 'informative')
lines.push('### Lighthouse audits below 90', '')
if (failed.length === 0) lines.push('None.', '')
else {
  lines.push('| Category | Audit | Score | Detail |', '|---|---|---|---|')
  for (const { category, audit } of failed) {
    lines.push(`| ${category} | ${audit.title} | ${Math.round(audit.score * 100)} | ${(audit.displayValue ?? '').replace(/\|/g, '/')} |`)
  }
  lines.push('')
}

// --- Accessibility sweep ---------------------------------------------------------

console.log('Accessibility sweep…')
const page = await browser.newPage()
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 })
await page.goto(BASE, { waitUntil: 'networkidle0' })
await page.keyboard.press('Escape')

const goTo = async (hash) => {
  await page.evaluate((target) => {
    location.hash = target
  }, hash)
  await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await new Promise((resolve) => setTimeout(resolve, 250))
}

// Put a route in the session so results, detail, map and chat have content.
await goTo('#/ruta')
for (const [field, query] of [['origin', 'alpha'], ['destination', 'foxtrot']]) {
  await page.waitForSelector(`[data-testid=${field}]`, { visible: true })
  await page.focus(`[data-testid=${field}]`)
  await page.keyboard.type(query)
  await page.keyboard.press('Enter')
}
await page.click('main:not([hidden]) button[type=submit]')
await page.waitForSelector('[data-testid=route-option]')
await goTo('#/chat')
await page.focus('[data-testid=chat-input]')
await page.keyboard.type('Alpha to Foxtrot')
await page.keyboard.press('Enter')
await page.waitForSelector('[data-testid=chat-option]')
await page.evaluate(() => document.activeElement?.blur())

const SCREENS = [
  ['Home', '#/'],
  ['Ruta', '#/ruta'],
  ['Results', '#/ruta/results'],
  ['Detail', '#/ruta/detail'],
  ['Trip placeholder', '#/ruta/trip'],
  ['Mapa', '#/mapa'],
  ['Paborito', '#/paborito'],
  ['Higit Pa', '#/higit'],
  ['Settings', '#/settings'],
  ['Mga Mode', '#/modes'],
  ['Offline Mode', '#/offline'],
  ['Setup', '#/setup'],
  ['About', '#/about'],
  ['Chat', '#/chat'],
]

const inspect = () =>
  page.evaluate(() => {
    const visible = (element) => {
      const box = element.getBoundingClientRect()
      const style = getComputedStyle(element)
      return box.width > 0 && box.height > 0 && style.visibility !== 'hidden' && element.closest('[hidden]') === null
    }
    const describe = (element) =>
      `${element.tagName.toLowerCase()}${element.id ? `#${element.id}` : ''} "${(element.getAttribute('aria-label') ?? element.textContent ?? '').trim().replace(/\s+/g, ' ').slice(0, 40)}"`
    const name = (element) =>
      (element.getAttribute('aria-label') ?? '').trim() ||
      (element.getAttribute('aria-labelledby') ? 'labelled' : '') ||
      (element.textContent ?? '').trim() ||
      (element.labels?.length ? 'labelled' : '') ||
      (element.getAttribute('title') ?? '').trim()

    const interactive = [...document.querySelectorAll('a[href], button, input, select, textarea, [role=switch], [role=option]')].filter(visible)
    const small = interactive
      .filter((element) => !element.classList.contains('sr-only'))
      .filter((element) => {
        // A control inside a larger label or link uses that as its target.
        const target = element.closest('label') ?? element
        const box = target.getBoundingClientRect()
        return box.width < 43.5 || box.height < 43.5
      })
      .map((element) => {
        const box = (element.closest('label') ?? element).getBoundingClientRect()
        return `${describe(element)} ${Math.round(box.width)}x${Math.round(box.height)}`
      })
    const unnamed = interactive.filter((element) => !name(element)).map(describe)
    const images = [...document.querySelectorAll('img')].filter(visible)
    const noAlt = images.filter((image) => !image.hasAttribute('alt')).map((image) => image.src.split('/').pop())
    const icons = [...document.querySelectorAll('svg')].filter(visible)
    const exposedIcons = icons.filter((icon) => icon.getAttribute('aria-hidden') !== 'true' && !icon.getAttribute('aria-label') && icon.getAttribute('role') !== 'img').length
    const root = document.scrollingElement
    return {
      interactive: interactive.length,
      small,
      unnamed,
      noAlt,
      exposedIcons,
      horizontalOverflow: root.scrollWidth - root.clientWidth,
      headings: [...document.querySelectorAll('h1')].filter(visible).length,
    }
  })

const rows = []
for (const [name, hash] of SCREENS) {
  await goTo(hash)
  const normal = await inspect()

  // Text at 200%: the root font size doubles, as browser text scaling does.
  await page.evaluate(() => (document.documentElement.style.fontSize = '200%'))
  await new Promise((resolve) => setTimeout(resolve, 150))
  const large = await inspect()
  // Is every interactive control still reachable (not pushed off the side)?
  const clipped = await page.evaluate(() =>
    [...document.querySelectorAll('a[href], button, input, select, textarea')]
      .filter((element) => element.getBoundingClientRect().width > 0 && element.closest('[hidden]') === null)
      .filter((element) => {
        const box = element.getBoundingClientRect()
        return box.right > window.innerWidth + 1 || box.left < -1
      })
      .filter((element) => {
        // Horizontal scrollers (quick replies) may extend past the edge on purpose.
        let node = element.parentElement
        while (node) {
          if (/(auto|scroll)/.test(getComputedStyle(node).overflowX)) return false
          node = node.parentElement
        }
        return true
      }).length,
  )
  await page.evaluate(() => (document.documentElement.style.fontSize = ''))

  // Reduced motion: no animation or transition should run longer than a blink.
  await page.emulateMediaFeatures([{ name: 'prefers-reduced-motion', value: 'reduce' }])
  const moving = await page.evaluate(
    () =>
      [...document.querySelectorAll('*')].filter((element) => {
        if (element.closest('[hidden]')) return false
        const style = getComputedStyle(element)
        const longest = (value) => Math.max(0, ...value.split(',').map((part) => parseFloat(part) * (part.includes('ms') ? 1 : 1000)))
        return (style.animationName !== 'none' && longest(style.animationDuration) > 20) || longest(style.transitionDuration) > 20
      }).length,
  )
  await page.emulateMediaFeatures([{ name: 'prefers-reduced-motion', value: 'no-preference' }])

  // Focus order: Tab from the very top of the document and record where focus goes.
  // Fixed elements (the bottom nav) and items inside scroll areas (the chat log) are
  // compared by document order only, since their screen position is not meaningful.
  await page.evaluate(() => {
    window.scrollTo(0, 0)
    const start = document.createElement('span')
    start.id = 'audit-focus-start'
    start.tabIndex = -1
    document.body.prepend(start)
    start.focus()
  })
  const order = []
  for (let i = 0; i < Math.min(normal.interactive + 2, 30); i++) {
    await page.keyboard.press('Tab')
    const spot = await page.evaluate(() => {
      const element = document.activeElement
      if (!element || element === document.body) return null
      const box = element.getBoundingClientRect()
      let pinned = false
      for (let node = element; node && node !== document.body; node = node.parentElement) {
        const style = getComputedStyle(node)
        if (style.position === 'fixed' || /(auto|scroll)/.test(style.overflowY)) pinned = true
      }
      return { top: Math.round(box.top + window.scrollY), hidden: element.closest('[hidden]') !== null, pinned }
    })
    if (!spot) break
    order.push(spot)
  }
  await page.evaluate(() => document.getElementById('audit-focus-start')?.remove())
  const flow = order.filter((spot) => !spot.pinned)
  const backwards = flow.filter((spot, index) => index > 0 && spot.top < flow[index - 1].top - 60).length
  const focusHidden = order.filter((spot) => spot.hidden).length

  rows.push({ name, normal, large, clipped, moving, backwards, focusHidden, tabStops: order.length })
}

lines.push('## Accessibility sweep', '')
lines.push('Run on every screen at 390 x 844 with a route planned and one chat exchange. Tap targets are measured on the control or its enclosing label; the floor is 44 px.', '')
lines.push('| Screen | Controls | Under 44 px | No accessible name | Images without alt | Icons not hidden from readers | Overflow at 200% text (px) | Controls off-screen at 200% | Still animating under reduced motion | Focus jumps backwards | Focus lands on hidden element | Visible h1 |')
lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|')
for (const row of rows) {
  lines.push(`| ${row.name} | ${row.normal.interactive} | ${row.normal.small.length} | ${row.normal.unnamed.length} | ${row.normal.noAlt.length} | ${row.normal.exposedIcons} | ${Math.max(0, row.large.horizontalOverflow)} | ${row.clipped} | ${row.moving} | ${row.backwards} | ${row.focusHidden} | ${row.normal.headings} |`)
}
lines.push('')
const details = rows.flatMap((row) => [
  ...row.normal.small.map((item) => `- ${row.name}: under 44 px: ${item}`),
  ...row.normal.unnamed.map((item) => `- ${row.name}: no accessible name: ${item}`),
  ...row.normal.noAlt.map((item) => `- ${row.name}: image without alt: ${item}`),
])
lines.push('### Findings', '')
lines.push(details.length ? details.join('\n') : 'None.', '')

// --- Contrast of the token pairs in use --------------------------------------------

const tokens = Object.fromEntries(
  [...readFileSync('src/styles/tokens.css', 'utf8').matchAll(/--color-([a-z-]+): (#[0-9A-F]{6})/g)].map((match) => [match[1], match[2]]),
)
const luminance = (hex) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255).map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const contrast = (a, b) => {
  const [hi, lo] = [luminance(tokens[a]), luminance(tokens[b])].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}
// Text colour on background colour, as used in the components.
const PAIRS = [
  ['ink-dark', 'surface-cream', 'body text on cards'],
  ['ink-muted', 'surface-cream', 'secondary text on cards'],
  ['ink-dark', 'surface-warm', 'text on banners and badges'],
  ['ink-muted', 'surface-warm', 'secondary text on banners'],
  ['ink-dark', 'accent-amber', 'primary button label'],
  ['surface-cream', 'brown-mid', 'dark button and user bubble'],
  ['surface-cream', 'bg-deep', 'text on the brown backdrop'],
  ['surface-cream', 'bg-gradient-top', 'text on the lightest backdrop area'],
  ['surface-cream', 'bg-gradient-glow', 'text on the sunburst glow'],
  ['surface-cream', 'bg-deeper', 'text on Offline Mode'],
  ['accent-amber', 'bg-deeper', 'amber link on Offline Mode'],
  ['brown-mid', 'surface-cream', 'brown link and icons on cards'],
  ['accent-terracotta', 'surface-cream', 'sample-data label on cards'],
]
lines.push('## Contrast of the colour pairs in use', '')
lines.push('WCAG AA needs 4.5:1 for normal text and 3:1 for large text and icons.', '')
lines.push('| Text | Background | Use | Ratio | AA normal text |', '|---|---|---|---|---|')
for (const [text, background, use] of PAIRS) {
  const ratio = contrast(text, background)
  lines.push(`| ${text} | ${background} | ${use} | ${ratio.toFixed(1)}:1 | ${ratio >= 4.5 ? 'pass' : ratio >= 3 ? 'large text only' : 'FAIL'} |`)
}
lines.push('', 'Text at reduced opacity on the backdrop (for example 75% cream) is not covered by this table.', '')

await browser.close()
await new Promise((resolve) => {
  server.httpServer.closeAllConnections?.()
  server.httpServer.close(resolve)
})

if (existsSync('docs/audit-notes.md')) lines.push(readFileSync('docs/audit-notes.md', 'utf8').trim(), '')
writeFileSync('docs/audit.md', lines.join('\n'))
console.log('Wrote docs/audit.md')
console.log(lines.filter((line) => line.startsWith('| ') || line.startsWith('- ')).join('\n'))
