// Usage: npm run bench -- <model-id> [<model-id> ...]     (no ids: every candidate)
//        npm run bench -- --report-only                    (rebuild the report from saved results)
// Runs the dev /bench page in headless Chrome with WebGPU and saves each model's
// result to docs/benchmark/<model-id>.json, then rebuilds docs/model-benchmark.md.
// The first run of a model downloads it (hundreds of MB) into .cache/bench-profile.
// Nothing is mocked: a model that fails to load is recorded as failed.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import puppeteer from 'puppeteer-core'
import { createServer } from 'vite'
import { findChrome } from './lib/browser.mjs'

const PORT = 5197
const OUT = 'docs/benchmark'
const PROFILE = '.cache/bench-profile'
const TIMEOUT_MS = 45 * 60 * 1000

mkdirSync(OUT, { recursive: true })
mkdirSync(PROFILE, { recursive: true })

const reportOnly = process.argv.includes('--report-only')
if (!reportOnly) await runModels(process.argv.slice(2))
writeReport()

async function runModels(requested) {

const server = await createServer({ server: { port: PORT, strictPort: true }, logLevel: 'silent' })
await server.listen()
const browser = await puppeteer.launch({
  executablePath: findChrome(),
  headless: true,
  userDataDir: PROFILE,
  args: ['--enable-unsafe-webgpu', '--ignore-gpu-blocklist'],
  protocolTimeout: TIMEOUT_MS,
})

async function runModel(modelId) {
  const page = await browser.newPage()
  page.on('pageerror', (error) => console.log(`  page error: ${error.message}`))
  await page.goto(`http://localhost:${PORT}/?model=${encodeURIComponent(modelId)}#/dev/bench`, {
    waitUntil: 'domcontentloaded',
  })
  await page.keyboard.press('Escape')
  await page.waitForFunction(
    (id) => document.querySelector('select[name=model]')?.value === id,
    { timeout: 60000 },
    modelId,
  )
  const gpu = await page.evaluate(async () => {
    const adapter = await navigator.gpu?.requestAdapter()
    return adapter ? `${adapter.info?.vendor ?? '?'} ${adapter.info?.architecture ?? ''}`.trim() : null
  })
  if (!gpu) throw new Error('WebGPU adapter not available in headless Chrome')

  await page.click('[data-testid=bench-run]')
  let last = ''
  const started = Date.now()
  for (;;) {
    const state = await page.evaluate(() => window.__paraBench)
    if (state?.message && state.message !== last) {
      last = state.message
      // Progress lines are long; keep the log readable.
      if (!/^Loading \d+%/.test(last) || /0%|25%|50%|75%|100%/.test(last.slice(0, 13))) console.log(`  ${last.slice(0, 110)}`)
    }
    if (state?.status === 'done') {
      await page.close()
      return { ...state.result, gpu, userAgent: await browser.userAgent() }
    }
    if (state?.status === 'error') throw new Error(state.message)
    if (Date.now() - started > TIMEOUT_MS) throw new Error('Timed out')
    await new Promise((resolve) => setTimeout(resolve, 2000))
  }
}

let models = requested
if (models.length === 0) {
  const page = await browser.newPage()
  await page.goto(`http://localhost:${PORT}/#/dev/bench`, { waitUntil: 'domcontentloaded' })
  await page.waitForFunction(() => document.querySelectorAll('select[name=model] option').length > 0, { timeout: 60000 })
  models = await page.$$eval('select[name=model] option', (options) => options.map((option) => option.value))
  await page.close()
}

for (const modelId of models) {
  console.log(`\n${modelId}`)
  try {
    const result = await runModel(modelId)
    // Keep the download size from the run that actually downloaded the model.
    const file = `${OUT}/${modelId}.json`
    if (result.downloadBytes === null && existsSync(file)) {
      result.downloadBytes = JSON.parse(readFileSync(file, 'utf8')).downloadBytes ?? null
    }
    writeFileSync(file, JSON.stringify(result, null, 2) + '\n')
    console.log(`  saved ${file}`)
  } catch (error) {
    console.log(`  FAILED: ${error.message}`)
    writeFileSync(`${OUT}/${modelId}.json`, JSON.stringify({ modelId, failed: error.message, ranAt: new Date().toISOString() }, null, 2) + '\n')
  }
}

await browser.close()
await server.close()
}

// --- Report -----------------------------------------------------------------

function writeReport() {
const results = readdirSync(OUT)
  .filter((file) => file.endsWith('.json'))
  .map((file) => JSON.parse(readFileSync(`${OUT}/${file}`, 'utf8')))
const good = results.filter((result) => !result.failed).sort((a, b) => a.label.localeCompare(b.label))
const failed = results.filter((result) => result.failed)
const percent = (value) => `${Math.round(value * 100)}%`
const megabytes = (bytes) => (bytes ? `${Math.round(bytes / 1048576)} MB` : 'not measured')

const lines = [
  '# Model benchmark',
  '',
  'Generated by `npm run bench`. Do not edit by hand.',
  '',
  'Each model ran on-device through WebLLM (WebGPU) over the 50 seed queries in `tests/taglish-50.json`, against the SYNTHETIC sample pack. Temperature 0, JSON constrained by schema, one retry on invalid JSON.',
  '',
  '**Read this before trusting the numbers**',
  '- The 50 queries are a seed set written by the coding agent, not real rider phrasings. The rules were tuned on the same set, so the "Rules only" row is a regression guard, not an accuracy claim.',
  '- Landmarks are synthetic names (SYN Alpha Terminal and so on). Real place names will behave differently.',
  '- Timings come from one laptop GPU in headless Chrome. Phones will be much slower.',
  '- Download size is the growth of browser storage across the download, so it includes the model library.',
  '',
]
if (good.length > 0) {
  lines.push(`Hardware: ${good[0].gpu} GPU. Browser: ${good[0].userAgent}.`, '')
  lines.push('## LLM lane alone (model parses every query)', '')
  lines.push('| Model | O/D exact | Preference | Avoid | Asks when unclear | All fields | Invalid JSON | p50 | p95 | Tokens/s | Load (cached) | Download | License |')
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|')
  for (const r of good) {
    lines.push(`| ${r.label} | ${percent(r.llmOnly.places)} | ${percent(r.llmOnly.preference)} | ${percent(r.llmOnly.avoid)} | ${percent(r.llmOnly.clarification)} | ${percent(r.llmOnly.exact)} | ${r.invalidJson} | ${Math.round(r.p50Ms)} ms | ${Math.round(r.p95Ms)} ms | ${r.tokensPerSecond ? r.tokensPerSecond.toFixed(0) : 'n/a'} | ${r.wasCached ? `${(r.loadMs / 1000).toFixed(1)} s` : `not measured (${(r.loadMs / 1000).toFixed(0)} s with download)`} | ${megabytes(r.downloadBytes)} | ${r.license} |`)
  }
  lines.push('', '## Hybrid (what the app does: rules first, model only when rules cannot finish)', '')
  lines.push('| Model | O/D exact | Preference | Avoid | Asks when unclear | All fields | Queries sent to the model |')
  lines.push('|---|---|---|---|---|---|---|')
  const rules = good[0].rulesOnly
  lines.push(`| Rules only, no model | ${percent(rules.places)} | ${percent(rules.preference)} | ${percent(rules.avoid)} | ${percent(rules.clarification)} | ${percent(rules.exact)} | 0 |`)
  for (const r of good) {
    lines.push(`| ${r.label} | ${percent(r.hybrid.places)} | ${percent(r.hybrid.preference)} | ${percent(r.hybrid.avoid)} | ${percent(r.hybrid.clarification)} | ${percent(r.hybrid.exact)} | ${r.hybridLlmCalls} of ${r.queries} |`)
  }
  lines.push('', '## Queries each model got wrong (LLM lane alone)', '')
  for (const r of good) lines.push(`- ${r.label}: ${r.llmOnly.misses.join(', ') || 'none'}`)
  lines.push('', 'Model ids: ' + good.map((r) => `\`${r.modelId}\` (run ${r.ranAt.slice(0, 10)})`).join(', ') + '.')
}
if (failed.length > 0) {
  lines.push('', '## Failed runs', '')
  for (const r of failed) lines.push(`- \`${r.modelId}\`: ${r.failed}`)
}
lines.push('', '## Not benchmarked', '', '- Gemma 3 1B IT: not in the model list of the installed WebLLM version, so it could not be run.', '')
// The recommendation is a human judgement kept in its own file and appended here.
if (existsSync(`${OUT}/recommendation.md`)) lines.push(readFileSync(`${OUT}/recommendation.md`, 'utf8').trim(), '')
writeFileSync('docs/model-benchmark.md', lines.join('\n'))
console.log('\nWrote docs/model-benchmark.md')
}
