// Usage: npm run tokens
// Samples the Tsupher palette from design/reference/ and writes
// src/styles/tokens.css (Tailwind v4 @theme tokens). Each value is the median
// of a small box around the listed pixel, so re-running gives the same result.
import { writeFileSync } from 'node:fs'
import sharp from 'sharp'

const SHOWCASE = 'Para! Commute Copilot UI Showcase.png'
const R = 3

// token, source file, x, y, what was sampled
const SAMPLES = [
  ['bg-deep', SHOWCASE, 60, 70, 'splash backdrop, top'],
  ['bg-deeper', SHOWCASE, 400, 650, 'Offline Mode backdrop'],
  ['bg-gradient-top', 'Logo.png', 1000, 300, 'logo tile gradient, middle'],
  ['bg-gradient-glow', 'Logo.png', 1900, 80, 'logo tile gradient, lightest corner'],
  ['surface-cream', SHOWCASE, 470, 315, 'Plan a Route tile'],
  ['surface-warm', SHOWCASE, 520, 440, '100% Offline banner'],
  ['accent-amber', SHOWCASE, 450, 908, 'Okay button'],
  ['accent-amber-soft', SHOWCASE, 1290, 108, 'Transit Line tab'],
  ['accent-terracotta', 'Para_.png', 900, 330, 'mascot roof stripe'],
  ['brown-mid', SHOWCASE, 620, 228, 'mic button'],
  ['ok-green', SHOWCASE, 893, 83, 'Offline status dot'],
]

// Text colours cannot be sampled reliably (anti-aliased glyphs), so the darkest
// pixels of a heading are used for ink-dark, and ink-muted is derived from it.
const INK_DARK = [SHOWCASE, 1012, 108, 6, '"Imus → Cubao" heading, darkest pixels']

const cache = new Map()
async function load(file) {
  if (!cache.has(file)) {
    cache.set(
      file,
      await sharp(`design/reference/${file}`).removeAlpha().raw().toBuffer({ resolveWithObject: true }),
    )
  }
  return cache.get(file)
}

async function pixels(file, x, y, r) {
  const { data, info } = await load(file)
  const list = []
  for (let j = y - r; j <= y + r; j++) {
    for (let i = x - r; i <= x + r; i++) {
      const o = (j * info.width + i) * 3
      list.push([data[o], data[o + 1], data[o + 2]])
    }
  }
  return list
}

const hex = (rgb) => '#' + rgb.map((v) => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase()
const median = (list) => [0, 1, 2].map((c) => list.map((p) => p[c]).sort((a, b) => a - b)[list.length >> 1])

function luminance([r, g, b]) {
  const lin = (v) => {
    const s = v / 255
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4
  }
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
}
const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

const tokens = []
for (const [name, file, x, y, what] of SAMPLES) {
  tokens.push({ name, rgb: median(await pixels(file, x, y, R)), note: `${what} (${file} @ ${x},${y})` })
}

const [inkFile, inkX, inkY, inkR, inkWhat] = INK_DARK
const inkPixels = (await pixels(inkFile, inkX, inkY, inkR)).sort((a, b) => a[0] + a[1] + a[2] - (b[0] + b[1] + b[2]))
const darkest = inkPixels.slice(0, inkPixels.length >> 3)
const inkDark = [0, 1, 2].map((c) => darkest.reduce((sum, p) => sum + p[c], 0) / darkest.length)
tokens.push({ name: 'ink-dark', rgb: inkDark, note: `${inkWhat} (${inkFile} @ ${inkX},${inkY})` })

// ink-muted: blend ink-dark toward cream until contrast on cream is just above 5:1 (WCAG AA is 4.5).
const cream = tokens.find((token) => token.name === 'surface-cream').rgb
let inkMuted = inkDark
for (let t = 0.6; t >= 0; t -= 0.01) {
  const mix = inkDark.map((v, c) => v + (cream[c] - v) * t)
  if (contrast(mix, cream) >= 5) {
    inkMuted = mix
    break
  }
}
tokens.push({ name: 'ink-muted', rgb: inkMuted, note: 'derived: ink-dark blended toward surface-cream, 5:1 contrast on cream' })

const get = (name) => tokens.find((token) => token.name === name).rgb
const lines = [
  '/* GENERATED by scripts/sample-tokens.mjs from design/reference/. Do not edit by hand. */',
  '',
  '@theme {',
  ...tokens.map((token) => `  --color-${token.name}: ${hex(token.rgb)}; /* ${token.note} */`),
  '  --color-on-deep: var(--color-surface-cream);',
  '  --color-line: color-mix(in srgb, var(--color-ink-dark) 14%, transparent);',
  '  --color-line-on-deep: color-mix(in srgb, var(--color-surface-cream) 18%, transparent);',
  '}',
  '',
  '/* Contrast (WCAG): ',
  `   ink-dark on surface-cream   ${contrast(get('ink-dark'), cream).toFixed(1)}:1`,
  `   ink-muted on surface-cream  ${contrast(get('ink-muted'), cream).toFixed(1)}:1`,
  `   ink-dark on accent-amber    ${contrast(get('ink-dark'), get('accent-amber')).toFixed(1)}:1`,
  `   surface-cream on bg-deep    ${contrast(cream, get('bg-deep')).toFixed(1)}:1`,
  `   surface-cream on brown-mid  ${contrast(cream, get('brown-mid')).toFixed(1)}:1`,
  `   accent-amber on bg-deep     ${contrast(get('accent-amber'), get('bg-deep')).toFixed(1)}:1`,
  `   accent-amber on cream       ${contrast(get('accent-amber'), cream).toFixed(1)}:1 (never use amber text on cream)`,
  '*/',
  '',
]
writeFileSync('src/styles/tokens.css', lines.join('\n'))
console.log(lines.join('\n'))
