// Every user-facing string lives here. Taglish, warm, short.
// The mascot and AI guide is Tsupher. Never write mockup values (fares, times, places) here.

export const copy = {
  app: {
    name: 'Para!',
    subtitle: 'Commute Copilot',
    tagline: ['Tamang ruta.', 'Tamang sakay.', 'Laging kasama ka.'],
    mascot: 'Tsupher',
    sampleData: 'SAMPLE DATA, not verified',
  },
  splash: {
    skip: 'I-tap para magpatuloy',
  },
  nav: {
    label: 'Pangunahing navigation',
    home: 'Home',
    ruta: 'Ruta',
    mapa: 'Mapa',
    paborito: 'Paborito',
    higit: 'Higit Pa',
    back: 'Bumalik',
  },
  status: {
    online: 'Online',
    offline: 'Offline',
  },
  home: {
    greeting: 'Kumusta!',
    intro: 'Ako si Tsupher! Handang tumulong sa iyong biyahe. Saan ka papunta?',
    promptLabel: 'Itanong kay Tsupher',
    promptPlaceholder: 'Type o magsalita ng Taglish. Saan ka papunta?',
    promptSubmit: 'Itanong',
    promptNotYet: 'Hindi pa makasagot si Tsupher dito. Gamitin muna ang Plan a Route.',
    micDisabled: 'Boses: hindi pa gumagana',
    planTitle: 'Plan a Route',
    planSub: '(Jeep, UV, Bus, MRT/LRT)',
    voiceTitle: 'Voice Chat',
    voiceSub: 'Kausapin si Tsupher',
    voiceSheetTitle: 'Malapit na ang Voice Chat',
    voiceSheetBody:
      'Tinuturuan pa si Tsupher makinig. Sa ngayon, i-type muna ang tanong mo o gamitin ang Plan a Route.',
    voiceSheetOk: 'Sige, Tsupher!',
    offlineTitle: '100% Offline',
    offlineBody:
      'Lahat ng info ay nasa telepono mo. Walang data na kailangan. Nasa phone mo lang ang lokasyon mo.',
  },
  offline: {
    title: 'Offline Mode',
    body: 'Gumagana ang Para! nang walang internet.',
    rows: {
      gps: { label: 'GPS / Lokasyon', value: 'Hindi kailangan' },
      search: { label: 'Search / Query', value: 'Naka-save sa phone' },
      ai: { label: 'AI Assistant', value: 'Hindi pa naka-install' },
    },
    yes: 'Handa',
    no: 'Wala pa',
    ok: 'Okay',
    bytesSent: 'Bytes sent',
    bytesNote: 'sukat ng app',
    bytesExplain:
      'Bilang ito ng app mismo. Ang tunay na patunay ay ang Network tab ng devtools.',
    private: 'Pribado at Ligtas',
    connection: 'Koneksyon ngayon',
  },
  higit: {
    title: 'Higit Pa',
    modes: { label: 'Mga Mode', sub: 'Mas mura, iwas traffic, custom' },
    offline: { label: 'Offline Mode', sub: 'Tingnan kung ano ang gumagana nang walang internet' },
    settings: { label: 'Settings', sub: 'Wika at unit' },
    about: { label: 'About / Disclosure', sub: 'Mga library, model at pinagkunan ng data' },
    devRouter: { label: 'Router harness', sub: 'Dev only' },
    devComponents: { label: 'Components', sub: 'Dev only' },
    soon: 'Malapit na',
  },
  stub: {
    title: 'Ginagawa pa ito',
    paborito: 'Dito mase-save ang mga paborito mong ruta.',
  },
  units: {
    min: 'min',
    hour: 'oras',
    km: 'km',
  },
  mode: {
    jeepney: 'Jeepney',
    modern_jeepney: 'Modern Jeepney',
    uv: 'UV Express',
    bus: 'Bus',
    train: 'MRT/LRT',
    walk: 'Lakad',
  },
  pref: {
    cheapest: 'Mas mura',
    fastest: 'Mas mabilis',
    fewest_transfers: 'Pinakakaunting sakay',
    custom: 'Custom',
  },
  badge: {
    unverified: 'Hindi pa verified',
    simulated: 'Simulated',
    chosen: 'Pinili mo',
  },
  plan: {
    title: 'Plan a Route',
    modesLink: 'Mga Mode',
    loading: 'Binubuksan ang route pack…',
    packError: 'Hindi mabuksan ang route pack sa phone na ito.',
    origin: 'Saan ka galing?',
    destination: 'Saan ka papunta?',
    pickerPlaceholder: 'I-type ang lugar',
    pickerEmpty: 'Walang tugmang lugar sa route pack.',
    pickerAlias: 'kilala rin bilang',
    swap: 'Pagpalitin ang galing at papunta',
    preference: 'Ano ang mas mahalaga?',
    search: 'Hanap',
    searching: 'Hinahanap…',
    needBoth: 'Piliin muna ang pinanggalingan at pupuntahan.',
    activeAvoid: 'Iwas EDSA (simulated)',
    activeCustom: 'Custom Preference',
  },
  results: {
    title: 'Mga Ruta',
    found: (count: number) => (count === 1 ? '1 opsyon' : `${count} opsyon`),
    rides: (count: number) => `${count} sakay`,
    transfers: (count: number) => (count === 0 ? 'Walang lipat' : `${count} lipat`),
    walkOnly: 'Lakad lang',
    asOf: (date: string) => `Pamasahe as of ${date}`,
    noFare: 'Walang pamasahe',
    simulatedNote: 'Simulation ito batay sa iniwasan mo. Hindi alam ng app ang totoong sarado o traffic.',
    emptyTitle: 'Walang nahanap na ruta',
    back: 'Baguhin ang hanap',
  },
  reason: {
    unknown_origin: 'Hindi ko kilala ang pinanggalingan. Pumili mula sa listahan.',
    unknown_destination: 'Hindi ko kilala ang pupuntahan. Pumili mula sa listahan.',
    same_origin_destination: 'Pareho ang pinanggalingan at pupuntahan mo.',
    origin_avoided: 'Kasama sa iniiwasan mo ang pinanggalingan.',
    destination_avoided: 'Kasama sa iniiwasan mo ang pupuntahan.',
    no_path: 'Walang rutang nagdudugtong sa dalawang lugar na ito sa route pack.',
  },
  detail: {
    title: 'Detalye ng Ruta',
    favorite: 'I-save sa Paborito (malapit na)',
    board: 'Sakay',
    alight: 'Baba',
    fareButton: 'Paano nakuha ang pamasahe?',
    fareSheetTitle: 'Hati ng pamasahe',
    base: (km: number) => `Base (unang ${km} km)`,
    extra: (km: number, perKm: string) => `Dagdag: ${km} km × ${perKm}`,
    unrounded: 'Bago i-round',
    legFare: 'Pamasahe',
    total: 'Kabuuan',
    effective: 'Effective date',
    source: 'Pinagkunan',
    rounding: 'Rounding',
    fareDisclaimer:
      'Reference lang ito. Ang nakapaskil na fare matrix sa sasakyan ang masusunod.',
    notesTitle: 'Tandaan:',
    start: 'Simulan ang Ruta',
    seeMap: 'Tingnan sa mapa',
    none: 'Wala pang napiling ruta. Maghanap muna.',
  },
  trip: {
    title: 'Trip mode',
    body: 'Ginagawa pa ang Trip mode. Dito ka gagabayan ni Tsupher habang nasa biyahe.',
    back: 'Bumalik sa detalye',
  },
  modes: {
    title: 'Mga Mode',
    intro: 'Para sa mas magandang biyahe',
    cheap: { label: 'Mas Mura Mode', sub: 'Ipakita ang pinakamurang ruta.' },
    avoidEdsa: {
      label: 'Iwas Traffic / Iwas EDSA',
      sub: 'Maghanap ng alternatibong ruta na hindi dumadaan sa EDSA.',
      note: 'Simulated: ikaw ang nagsabing iwasan ito. Hindi alam ng app ang totoong traffic.',
    },
    custom: {
      label: 'Custom Preference',
      sub: 'Ikaw ang magtitimbang ng pamasahe, oras at dami ng lipat.',
      fare: 'Pamasahe',
      minutes: 'Oras',
      transfers: 'Dami ng lipat',
      scale: (value: number) => `${value} sa 10`,
    },
    on: 'Naka-on',
    off: 'Naka-off',
    settings: 'Mga Setting',
    language: { label: 'Wika', value: 'Taglish (Default)' },
    unit: { label: 'Unit', value: 'Piso at minuto' },
    done: 'Okay',
  },
  map: {
    title: 'Mapa ng Ruta',
    schematic: 'Schematic lang ito mula sa route pack. Hindi ito totoong mapa ng kalsada.',
    noRoute: 'Wala pang napiling ruta. Ipinapakita ang buong network.',
    planFirst: 'Mag-plan ng ruta',
    zoomIn: 'Palakihin',
    zoomOut: 'Paliitin',
    reset: 'Ibalik ang view',
    origin: 'Simula',
    destination: 'Dulo',
    transfer: 'Lipatan',
    legend: 'Legend',
    describe: (from: string, to: string, legs: number) =>
      `Schematic na mapa mula ${from} hanggang ${to}, ${legs} bahagi.`,
    describeNetwork: 'Schematic na mapa ng buong route pack.',
  },
  about: {
    title: 'About',
    intro:
      'Ang Para! ay offline na katulong sa commute. Walang account, walang analytics, walang lumalabas sa device na ito.',
    libraries: 'Mga library',
    models: 'Mga model',
    modelsNone: 'Wala pa. Walang AI model sa build na ito.',
    data: 'Pinagkunan ng data',
    dataLoading: 'Binabasa ang local database…',
    dataNote: 'Synthetic na test network lang. Walang totoong ruta, terminal o pamasahe.',
    fonts: 'Mga font',
    art: 'Art',
    artNote:
      'Ang mga sprite ni Tsupher ay awtomatikong ginupit mula sa reference sheet (draft). Placeholder pa ang wordmark.',
  },
  tsupher: {
    hero: 'Si Tsupher, ang jeepney na gabay mo',
    happy: 'Si Tsupher, nakangiti',
    thinking: 'Si Tsupher, nag-iisip',
    map: 'Si Tsupher, nagbabasa ng mapa',
    'thumbs-up': 'Si Tsupher, naka-thumbs up',
    confused: 'Si Tsupher, nalilito',
    sad: 'Si Tsupher, malungkot',
    sign: 'Si Tsupher, may hawak na karatula',
    driving: 'Si Tsupher, umaandar',
    luggage: 'Si Tsupher, may dalang maleta',
    jumping: 'Si Tsupher, tumatalon sa tuwa',
    love: 'Si Tsupher, kinikilig',
    excited: 'Si Tsupher, excited',
  },
} as const
