// Every user-facing string lives here. Taglish, warm, short.
// The mascot and AI guide is Tsupher. Never write mockup values (fares, times, places) here.

export const copy = {
  app: {
    name: 'Para!',
    subtitle: 'Commute Copilot',
    tagline: ['Tamang ruta.', 'Tamang sakay.', 'Laging kasama ka.'],
    mascot: 'Tsupher',
    sampleData: 'SAMPLE DATA, not verified',
  },
  splash: {
    start: 'Simulan',
  },
  nav: {
    label: 'Pangunahing navigation',
    home: 'Home',
    ruta: 'Ruta',
    mapa: 'Mapa',
    paborito: 'Paborito',
    higit: 'Higit Pa',
    back: 'Bumalik',
  },
  status: {
    online: 'Online',
    offline: 'Offline',
  },
  home: {
    greeting: 'Kumusta!',
    intro: 'Ako si Tsupher! Handang tumulong sa iyong biyahe. Saan ka papunta?',
    promptLabel: 'Itanong kay Tsupher',
    promptPlaceholder: 'Type o magsalita ng Taglish. Saan ka papunta?',
    promptSubmit: 'Itanong',
    planTitle: 'Plan a Route',
    planSub: '(Jeep, UV, Bus, MRT/LRT)',
    voiceTitle: 'Voice Chat',
    voiceSub: 'Kausapin si Tsupher',
    savedTitle: 'My Saved Routes',
    savedSub: 'Tingnan ang mga na-save',
    tipTitle: 'Tsupher Tip!',
    tipBody: 'Mas mura ba? Buksan ang "Mas Mura Mode" para unahin ang pinakamurang ruta.',
    placesTitle: 'Mga Na-save na Lugar',
    offlineTitle: '100% Offline',
    offlineBody:
      'Lahat ng info ay nasa telepono mo. Walang data na kailangan. Nasa phone mo lang ang lokasyon mo.',
  },
  offline: {
    title: 'Offline Mode',
    body: 'Gumagana ang Para! nang walang internet. Ito ang kasalukuyang lagay ng app sa phone mo.',
    rows: {
      sw: 'Offline na kopya ng app',
      pack: 'Route pack',
      ai: 'AI Assistant',
      voice: 'Boses (Whisper)',
      inference: 'Huling sagot ng AI',
      crossOrigin: 'Request sa ibang server mula nang buksan',
    },
    checking: 'Tinitingnan…',
    swActive: 'Aktibo ang service worker',
    swInstalling: 'Ini-install pa. I-reload ang app.',
    swNone: 'Hindi naka-install',
    swNoneNote: 'Kailangan ng naka-build na bersyon. Hindi ito gumagana sa dev server.',
    packLoaded: (version: string, routes: number, fareAsOf: string) =>
      `Bersyon ${version} · ${routes} ruta · pamasahe as of ${fareAsOf}`,
    packFailed: 'Hindi mabuksan',
    aiInstalled: (model: string, size: string | null) => (size ? `${model} · ${size}` : model),
    aiAbsent: 'Hindi pa naka-install',
    voiceBackend: (backend: string) => `Backend: ${backend}, sa device mismo`,
    voiceNote: 'Sa device mismo tumatakbo: WebGPU kung meron, WASM kung wala.',
    voiceLast: (ms: number, seconds: string) => `huling transcription ${ms} ms para sa ${seconds} s na audio`,
    aiDownloading: (percent: number) => `Dina-download: ${percent}%`,
    aiFailed: 'Hindi nagbukas ang model',
    noWebGpu: 'Walang WebGPU ang browser na ito',
    backendWebGpu: 'Backend: WebGPU, sa device mismo',
    rulesFallback: 'Simpleng pag-intindi (rules) ang gamit, walang AI model.',
    inference: (ms: number, tokensPerSecond: number | null) =>
      tokensPerSecond ? `${ms} ms · ${tokensPerSecond} tokens/s` : `${ms} ms`,
    noInference: 'Wala pa sa session na ito',
    notMeasurable: 'Hindi masukat sa browser na ito',
    crossOriginNote: 'Bilang ng browser mismo, kasama ang mga library.',
    crossOriginHosts: (hosts: string) => `Papunta sa: ${hosts}`,
    yes: 'Oo',
    no: 'Hindi',
    ok: 'Okay',
    bytesSent: 'Bytes sent',
    bytesNote: 'sukat ng app',
    bytesExplain:
      'Bilang ito ng app mismo. Ang tunay na patunay ay ang Network tab ng devtools.',
    private: 'Pribado at Ligtas',
    connection: 'Koneksyon ngayon',
  },
  stale: {
    short: 'Maaaring luma na ang pamasahe',
    long: (date: string, days: number) =>
      `Ang fare table ay as of ${date} (${days} araw na). Maaaring may bagong fare matrix. Tingnan ang nakapaskil sa sasakyan.`,
  },
  update: {
    title: 'May bagong bersyon ng Para!',
    action: 'I-update',
  },
  crash: {
    title: 'Naku, may nasira',
    body: 'Nagka-problema ang screen na ito. Ligtas ang data mo sa phone.',
    retry: 'Subukan ulit',
    home: 'Bumalik sa Home',
  },
  higit: {
    title: 'Higit Pa',
    modes: { label: 'Mga Mode', sub: 'Mas mura, iwas traffic, custom' },
    offline: { label: 'Offline Mode', sub: 'Tingnan kung ano ang gumagana nang walang internet' },
    settings: { label: 'Settings', sub: 'Unit, ambag, burahin ang data' },
    about: { label: 'About / Disclosure', sub: 'Mga library, model at pinagkunan ng data' },
    devRouter: { label: 'Router harness', sub: 'Dev only' },
    devComponents: { label: 'Components', sub: 'Dev only' },
    soon: 'Malapit na',
  },
  stub: {
    title: 'Ginagawa pa ito',
  },
  fav: {
    saveRoute: 'I-save ang ruta sa Paborito',
    removeRoute: 'Tanggalin ang ruta sa Paborito',
    savePlace: (name: string) => `I-save ang ${name} sa Paborito`,
    removePlace: (name: string) => `Tanggalin ang ${name} sa Paborito`,
    saved: 'Na-save sa Paborito!',
    removed: 'Tinanggal sa Paborito.',
    error: 'Hindi na-save. Subukan ulit.',
  },
  paborito: {
    title: 'Paborito',
    tabsLabel: 'Uri ng paborito',
    tabRoutes: 'Mga Ruta',
    tabAddress: 'Address',
    emptyRoutes: 'Wala ka pang naka-save na ruta. I-tap ang puso sa resulta o sa detalye ng ruta.',
    emptyAddress: 'Wala ka pang naka-save na lugar.',
    addressNote: 'Mga landmark lang sa route pack ang puwedeng i-save dito.',
    addLabel: 'Magdagdag ng landmark',
    from: 'Galing dito',
    to: 'Papunta dito',
    open: 'Buksan',
    missing: 'Wala na sa route pack na ito',
    otherPack: (version: string) => `Galing sa ibang bersyon ng route pack (${version}). Titingnan ulit ng router.`,
    recent: 'Kamakailang Hinanap',
    recentNote: 'Sa session na ito lang. Mawawala kapag isinara ang app.',
    recentEmpty: 'Wala pang hinahanap sa session na ito.',
    savedAt: (date: string) => `Na-save noong ${date}`,
  },
  report: {
    button: 'May mali ba?',
    title: 'May mali ba?',
    intro: 'Sabihin kung ano ang mali. Maaari mong dagdagan ng maikling tala. Sa phone mo lang ito mase-save.',
    issueLabel: 'Ano ang mali?',
    issues: {
      fare: 'Mali ang pamasahe',
      route: 'Mali ang ruta o ang sakayan',
      time: 'Mali ang oras',
      gone: 'Wala na o sarado ang ruta',
      other: 'Iba pa',
    },
    noteLabel: 'Tala (hindi kailangan)',
    notePlaceholder: 'Halimbawa: ₱15 ang singil ng driver',
    noteCount: (used: number, max: number) => `${used} sa ${max}`,
    submit: 'I-save sa phone',
    cancel: 'Kanselahin',
    savedTitle: 'Na-save sa phone mo',
    savedBody: 'Hindi ito ipinapadala kahit saan. Para ibigay sa team, i-export ang file sa Settings.',
    close: 'Okay',
    error: 'Hindi na-save. Subukan ulit.',
  },
  settings: {
    title: 'Settings',
    language: { label: 'Wika', value: 'Taglish lang ang available ngayon.', badge: 'Hindi pa available' },
    unitsTitle: 'Unit',
    unitsNote: 'Para sa mga screen ng ruta. Ang mga sagot ni Tsupher sa chat ay laging min, oras at km.',
    time: 'Oras',
    timeHm: 'Oras at min',
    timeMin: 'Min lang',
    distance: 'Distansya',
    distanceKm: 'Kilometro',
    distanceMi: 'Milya',
    sessionTitle: 'Session',
    sessionBody: 'Binubura ang usapan, ang hanap at ang Kamakailang Hinanap. Hindi gagalawin ang Paborito at ang mga setting.',
    sessionButton: 'I-reset ang session',
    sessionDone: 'Nabura na ang session.',
    contribTitle: 'Mga ambag ("May mali ba?")',
    contribBody:
      'Naka-save sa phone ang mga report. Walang awtomatikong pagpapadala: i-export ang file at ibigay sa team. Ang "sync now" ay export lang.',
    contribCount: (queued: number, total: number) => `${total} report · ${queued} hindi pa na-export`,
    exportJson: 'I-export (JSON)',
    exportCsv: 'I-export (CSV)',
    importLabel: 'I-import ang file ng team (JSON o CSV)',
    exported: (count: number, filename: string) => `Nagawa ang ${filename} (${count} report). Na-export na ito sa file, hindi pa ito natatanggap ng kahit sino.`,
    nothingToExport: 'Wala pang report na i-export.',
    imported: (added: number, duplicates: number, skipped: number) =>
      `Nadagdag: ${added}. Nandito na dati: ${duplicates}. Hindi tinanggap: ${skipped}.`,
    importErrors: {
      empty: 'Walang laman ang file.',
      format: 'Hindi ito file ng Para!. Kailangan ang JSON o CSV na galing sa export.',
      too_many: 'Masyadong marami ang report sa file (hanggang 1000).',
      read: 'Hindi mabasa ang file.',
      tooBig: 'Masyadong malaki ang file (hanggang 1 MB).',
    },
    dangerTitle: 'Burahin lahat ng data',
    dangerBody: 'Binubura sa phone na ito ang lahat ng sarili mong data. Hindi ito mababawi.',
    dangerButton: 'Burahin lahat ng data',
    confirmTitle: 'Sigurado ka ba?',
    confirmList: [
      'Lahat ng Paborito (ruta at landmark)',
      'Lahat ng report sa "May mali ba?"',
      'Ang mga setting (unit)',
      'Ang usapan, ang hanap at ang Kamakailang Hinanap',
    ],
    confirmKeeps: 'Hindi mabubura: ang route pack at ang offline na kopya ng app.',
    confirmModels: 'Burahin din ang na-download na AI model at voice model (kailangan ng internet para ma-download ulit)',
    confirmYes: 'Oo, burahin',
    confirmNo: 'Huwag muna',
    erased: 'Nabura na ang lahat ng sarili mong data.',
    eraseFailed: 'May hindi nabura. Subukan ulit.',
    storage: 'Lahat ng ito ay nasa phone mo lang. Walang account at walang pinapadala sa internet.',
  },
  voice: {
    mic: 'Magsalita kay Tsupher',
    listening: 'Makinig si Tsupher…',
    hint: 'Magsalita nang malinaw sa Taglish',
    finish: 'Tapusin',
    cancel: 'Kanselahin',
    transcribing: 'Iniintindi ang sinabi mo…',
    confirm: 'Ito ba ang ibig mong sabihin…?',
    typeInstead: 'I-type na lang',
    denied: 'Hindi pinayagan ang mikropono. Puwede mo pa ring i-type ang tanong mo.',
    noMic: 'Walang makuhang mikropono sa device na ito. I-type na lang ang tanong mo.',
    heardNothing: 'Wala akong narinig. Subukan ulit, o i-type na lang.',
    failed: 'Hindi gumana ang boses sa device na ito. I-type na lang ang tanong mo.',
    needModelTitle: 'Kailangan muna ng voice model',
    needModelBody:
      'I-download nang isang beses ang voice model sa Gisingin si Tsupher. Pagkatapos, gumagana ang boses kahit walang signal.',
    needModelAction: 'Pumunta sa Gisingin si Tsupher',
    privacy: 'Sa phone mo lang pinoproseso ang boses mo. Binubura agad ang audio pagkatapos intindihin.',
  },
  chat: {
    subtitle: 'Gabay mo sa commute, sa phone mo lang',
    logLabel: 'Usapan ninyo ni Tsupher',
    placeholder: 'Type o magsalita…',
    send: 'Ipadala',
    thinking: 'Nag-iisip si Tsupher',
    wakingModel: 'Ginigising ang model…',
    found: 'Sige! Ito ang nahanap ko:',
    refined: 'Ayan, inayos ko na:',
    whatIf: 'Simulation lang ito, batay sa sinabi mong iwasan. Hindi ko alam ang totoong sarado o traffic.',
    askOrigin: 'Saan ka manggagaling?',
    askDestination: 'Saan ka papunta?',
    askBoth: 'Saan ka galing, at saan ka papunta?',
    pickOne: 'Alin dito ang ibig mong sabihin?',
    unsupported:
      'Pasensya na, ruta at pamasahe lang ang kaya kong sagutin. Subukan: sabihin kung saan ka galing at saan ka papunta.',
    reset: 'Sige, bagong biyahe tayo. Saan ka papunta?',
    error: 'May nagkamali sa akin. Pakisubukan ulit.',
    modelFailed:
      'Hindi nagbukas ang AI model, kaya simpleng pag-intindi muna ang gamit ko. Gumagana pa rin ang ruta at pamasahe.',
    quickCheaper: 'Mas mura',
    quickFewer: 'Mas kaunting sakay',
    quickAvoid: (tag: string) => `Iwas ${tag}`,
    pickOrigin: (name: string) => `galing ${name}`,
    pickDestination: (name: string) => `papunta sa ${name}`,
  },
  setup: {
    title: 'Gisingin si Tsupher',
    checking: 'Tinitingnan ang phone mo…',
    absentTitle: 'Tulog pa si Tsupher',
    absentBody:
      'I-download nang isang beses ang AI model para maintindihan ni Tsupher ang Taglish mo, kahit walang signal.',
    choose: 'Piliin ang model',
    wifi: 'Mag-WiFi muna. Malaki ang file at isang beses lang ito ida-download.',
    start: 'Gisingin si Tsupher',
    retry: 'Ituloy ang download',
    downloadingTitle: 'Ginigising si Tsupher…',
    keepUsing: 'Puwede mong gamitin ang app habang nagda-download. Gumagana pa rin ang Plan a Route.',
    errorTitle: 'Naputol',
    errorBody: 'Hindi natapos. Itutuloy mula sa na-download na.',
    errorQuota: 'Kulang ang storage ng phone para sa model. Magbura muna ng ibang file, o pumili ng mas maliit na model.',
    errorMemory: 'Kulang ang memory ng device para patakbuhin ang model na ito. Pumili ng mas maliit na model.',
    totalDownload:
      'Kabuuang download: ang AI model at, kung gusto mo ng boses, ang voice model. Kasama na sa app ang route pack.',
    voiceTitle: 'Boses ni Tsupher',
    voiceAbsentBody:
      'I-download nang isang beses ang voice model (Whisper) para makapagsalita ka kay Tsupher, kahit walang signal.',
    voiceApprox: (megabytes: number) => `Mga ${megabytes} MB`,
    voiceStart: 'I-download ang boses',
    voiceDownloading: 'Dina-download ang boses…',
    voiceReadyTitle: 'Handa na ang boses',
    voiceRemove: 'Burahin ang voice model',
    voiceError: 'Hindi natapos ang voice model. Subukan ulit.',
    readyTitle: 'Gising na si Tsupher!',
    readyBody: 'Nasa phone mo na ang model. Hindi na kailangan ng internet.',
    model: 'Model',
    license: 'Lisensya',
    modelSize: 'Laki sa phone',
    unknownSize: 'Hindi nasukat',
    remove: 'Burahin ang model',
    unsupportedTitle: 'Walang WebGPU ang browser na ito',
    unsupportedBody:
      'Hindi mapapatakbo ang AI model dito. Gumagana pa rin ang Plan a Route at ang simpleng pag-intindi ng tanong.',
    storage: (used: string, quota: string) => `Gamit na storage: ${used} sa ${quota}`,
    persisted: 'protektado sa pagbura',
    notPersisted: 'maaaring burahin ng browser kapag puno na',
    privacy:
      'Ang download lang ng model ang gumagamit ng internet. Hindi ipinapadala ang tanong, boses, lokasyon o ruta mo.',
    homeTitle: 'Gisingin si Tsupher',
    homeBody: 'I-download ang AI model nang isang beses para mas maintindihan ka niya.',
  },
  units: {
    min: 'min',
    hour: 'oras',
    km: 'km',
    mi: 'mi',
  },
  mode: {
    jeepney: 'Jeepney',
    modern_jeepney: 'Modern Jeepney',
    uv: 'UV Express',
    bus: 'Bus',
    train: 'MRT/LRT',
    walk: 'Lakad',
  },
  pref: {
    cheapest: 'Mas mura',
    fastest: 'Mas mabilis',
    fewest_transfers: 'Pinakakaunting sakay',
    custom: 'Custom',
  },
  badge: {
    unverified: 'Hindi pa verified',
    simulated: 'Simulated',
    chosen: 'Pinili mo',
  },
  plan: {
    title: 'Plan a Route',
    modesLink: 'Mga Mode',
    loading: 'Binubuksan ang route pack…',
    packError: 'Hindi mabuksan ang route pack sa phone na ito.',
    origin: 'Saan ka galing?',
    destination: 'Saan ka papunta?',
    pickerPlaceholder: 'I-type ang lugar',
    pickerEmpty: 'Walang tugmang lugar sa route pack.',
    pickerAlias: 'kilala rin bilang',
    swap: 'Pagpalitin ang galing at papunta',
    preference: 'Ano ang mas mahalaga?',
    search: 'Hanap',
    searching: 'Hinahanap…',
    needBoth: 'Piliin muna ang pinanggalingan at pupuntahan.',
    activeAvoid: 'Iwas EDSA (simulated)',
    activeCustom: 'Custom Preference',
  },
  results: {
    title: 'Mga Ruta',
    found: (count: number) => (count === 1 ? '1 opsyon' : `${count} opsyon`),
    rides: (count: number) => `${count} sakay`,
    transfers: (count: number) => (count === 0 ? 'Walang lipat' : `${count} lipat`),
    walkOnly: 'Lakad lang',
    asOf: (date: string) => `Pamasahe as of ${date}`,
    noFare: 'Walang pamasahe',
    simulatedNote: 'Simulation ito batay sa iniwasan mo. Hindi alam ng app ang totoong sarado o traffic.',
    emptyTitle: 'Walang nahanap na ruta',
    back: 'Baguhin ang hanap',
  },
  reason: {
    unknown_origin: 'Hindi ko kilala ang pinanggalingan. Pumili mula sa listahan.',
    unknown_destination: 'Hindi ko kilala ang pupuntahan. Pumili mula sa listahan.',
    same_origin_destination: 'Pareho ang pinanggalingan at pupuntahan mo.',
    origin_avoided: 'Kasama sa iniiwasan mo ang pinanggalingan.',
    destination_avoided: 'Kasama sa iniiwasan mo ang pupuntahan.',
    no_path: 'Walang rutang nagdudugtong sa dalawang lugar na ito sa route pack.',
  },
  detail: {
    title: 'Detalye ng Ruta',
    board: 'Sakay',
    alight: 'Baba',
    fareButton: 'Paano nakuha ang pamasahe?',
    fareSheetTitle: 'Hati ng pamasahe',
    base: (km: number) => `Base (unang ${km} km)`,
    extra: (km: number, perKm: string) => `Dagdag: ${km} km × ${perKm}`,
    unrounded: 'Bago i-round',
    legFare: 'Pamasahe',
    total: 'Kabuuan',
    effective: 'Effective date',
    source: 'Pinagkunan',
    rounding: 'Rounding',
    fareDisclaimer:
      'Reference lang ito. Ang nakapaskil na fare matrix sa sasakyan ang masusunod.',
    notesTitle: 'Tandaan:',
    start: 'Simulan ang Ruta',
    seeMap: 'Tingnan sa mapa',
    none: 'Wala pang napiling ruta. Maghanap muna.',
  },
  trip: {
    title: 'Trip mode',
    back: 'Bumalik sa detalye',
    consentTitle: 'Gagabayan kita habang nasa biyahe',
    consentBody:
      'Hihingin ng phone ang lokasyon mo para masabi ni Tsupher kung malapit ka na sa babaan. Nasa phone mo lang ang lokasyon mo: hindi ito ipinapadala kahit saan at hindi sine-save.',
    consentLimit:
      'Hindi gumagana ang app sa background. Panatilihing bukas ang screen. Gising lang ang screen kung suportado ng phone mo.',
    useGps: 'Gamitin ang GPS ko',
    useSim: 'Simulated GPS (pang-demo)',
    simBanner: 'Simulated GPS: hindi ito totoong lokasyon mo.',
    simSpeed: 'Bilis ng simulation',
    simSpeedLabel: (kmh: number) => `${kmh} km/h`,
    leg: (index: number, total: number) => `Leg ${index} sa ${total}`,
    board: 'Sakay',
    nextLandmark: 'Susunod na landmark',
    toAlight: 'Layo sa babaan',
    alightAt: (name: string) => `Baba sa ${name}`,
    walkTo: (name: string) => `Maglakad papuntang ${name}`,
    meters: (value: number) =>
      value >= 1000 ? `${(value / 1000).toFixed(1)} km` : `${Math.round(value / 10) * 10} m`,
    progress: 'Progreso ng biyahe',
    waiting: 'Hinihintay ang GPS…',
    weakSignal: (accuracy: number) =>
      `Mahina ang GPS signal (±${Math.round(accuracy)} m). Hinihintay ang mas malinaw.`,
    denied: 'Hindi pinayagan ang lokasyon. Buksan ito sa settings ng browser, o gamitin ang Simulated GPS.',
    unavailable: 'Walang makuhang lokasyon ngayon. Subukan ulit sa labas, o gamitin ang Simulated GPS.',
    unsupported: 'Walang GPS ang browser na ito. Gamitin ang Simulated GPS.',
    awake: 'Gising ang screen.',
    awakeOff: 'Hindi magising ang screen. Baka mag-lock ito; buksan ulit kung kailangan.',
    alighted: 'Nakababa na ako',
    finish: 'Tapusin',
    stop: 'Itigil ang biyahe',
    alertTitle: 'Malapit na ang babaan!',
    alertDistance: (meters: string, name: string) => `${meters} na lang bago ang ${name}.`,
    bubble: 'Para po!',
    dismiss: 'Sige, Tsupher!',
    doneTitle: 'Nakarating ka na!',
    doneBody: 'Salamat sa pagsama kay Tsupher.',
    none: 'Wala pang napiling ruta. Maghanap muna.',
  },
  modes: {
    title: 'Mga Mode',
    intro: 'Para sa mas magandang biyahe',
    cheap: { label: 'Mas Mura Mode', sub: 'Ipakita ang pinakamurang ruta.' },
    avoidEdsa: {
      label: 'Iwas Traffic / Iwas EDSA',
      sub: 'Maghanap ng alternatibong ruta na hindi dumadaan sa EDSA.',
      note: 'Simulated: ikaw ang nagsabing iwasan ito. Hindi alam ng app ang totoong traffic.',
    },
    custom: {
      label: 'Custom Preference',
      sub: 'Ikaw ang magtitimbang ng pamasahe, oras at dami ng lipat.',
      fare: 'Pamasahe',
      minutes: 'Oras',
      transfers: 'Dami ng lipat',
      scale: (value: number) => `${value} sa 10`,
    },
    on: 'Naka-on',
    off: 'Naka-off',
    settings: 'Mga Setting',
    language: { label: 'Wika', value: 'Taglish (Default)' },
    unit: { label: 'Unit', value: 'Piso at minuto' },
    done: 'Okay',
  },
  map: {
    title: 'Mapa ng Ruta',
    schematic: 'Schematic lang ito mula sa route pack. Hindi ito totoong mapa ng kalsada.',
    noRoute: 'Wala pang napiling ruta. Ipinapakita ang buong network.',
    planFirst: 'Mag-plan ng ruta',
    zoomIn: 'Palakihin',
    zoomOut: 'Paliitin',
    reset: 'Ibalik ang view',
    origin: 'Simula',
    destination: 'Dulo',
    transfer: 'Lipatan',
    legend: 'Legend',
    features: 'Opsyonal na Feature',
    alertTitle: 'Drop-off Alert',
    alertSub: 'Sasabihan ka ni Tsupher kapag malapit na ang babaan. Buksan ang Trip mode.',
    describe: (from: string, to: string, legs: number) =>
      `Schematic na mapa mula ${from} hanggang ${to}, ${legs} bahagi.`,
    describeNetwork: 'Schematic na mapa ng buong route pack.',
  },
  about: {
    title: 'About',
    intro:
      'Ang Para! ay offline na katulong sa commute. Walang account, walang analytics, walang lumalabas sa device na ito.',
    libraries: 'Mga library',
    models: 'Mga model',
    modelsNote:
      'Hindi kasama sa app ang mga model. Dina-download lang ang pinili mo sa Gisingin si Tsupher: isang AI model (WebLLM, WebGPU) at, kung gusto mo ng boses, isang Whisper model (transformers.js, WebGPU o WASM). Sa device lang tumatakbo ang mga ito.',
    modelInstalled: 'Naka-install',
    data: 'Pinagkunan ng data',
    dataLoading: 'Binabasa ang local database…',
    dataNote: 'Synthetic na test network lang. Walang totoong ruta, terminal o pamasahe.',
    packVersion: (id: string, version: string) => `Route pack: ${id}, bersyon ${version}`,
    fareAsOf: (date: string) => `Pamasahe as of ${date}`,
    fonts: 'Mga font',
    art: 'Art',
    artNote:
      'Ang mga sprite ni Tsupher ay awtomatikong ginupit mula sa reference sheet (draft). Placeholder pa ang wordmark.',
  },
  tsupher: {
    hero: 'Si Tsupher, ang jeepney na gabay mo',
    happy: 'Si Tsupher, nakangiti',
    thinking: 'Si Tsupher, nag-iisip',
    map: 'Si Tsupher, nagbabasa ng mapa',
    'thumbs-up': 'Si Tsupher, naka-thumbs up',
    confused: 'Si Tsupher, nalilito',
    sad: 'Si Tsupher, malungkot',
    sign: 'Si Tsupher, may hawak na karatula',
    driving: 'Si Tsupher, umaandar',
    luggage: 'Si Tsupher, may dalang maleta',
    jumping: 'Si Tsupher, tumatalon sa tuwa',
    love: 'Si Tsupher, kinikilig',
    excited: 'Si Tsupher, excited',
  },
} as const
