// Every user-facing string lives here. Taglish, warm, short.
// The mascot and AI guide is Tsupher. Never write mockup values (fares, times, places) here.

export const copy = {
  app: {
    name: 'Para!',
    subtitle: 'Commute Copilot',
    tagline: ['Tamang ruta.', 'Tamang sakay.', 'Laging kasama ka.'],
    mascot: 'Tsupher',
    sampleData: 'SAMPLE DATA, not verified',
  },
  splash: {
    skip: 'I-tap para magpatuloy',
  },
  nav: {
    label: 'Pangunahing navigation',
    home: 'Home',
    ruta: 'Ruta',
    mapa: 'Mapa',
    paborito: 'Paborito',
    higit: 'Higit Pa',
    back: 'Bumalik',
  },
  status: {
    online: 'Online',
    offline: 'Offline',
  },
  home: {
    greeting: 'Kumusta!',
    intro: 'Ako si Tsupher! Handang tumulong sa iyong biyahe. Saan ka papunta?',
    promptLabel: 'Itanong kay Tsupher',
    promptPlaceholder: 'Type o magsalita ng Taglish. Saan ka papunta?',
    promptSubmit: 'Itanong',
    micDisabled: 'Boses: hindi pa gumagana',
    planTitle: 'Plan a Route',
    planSub: '(Jeep, UV, Bus, MRT/LRT)',
    voiceTitle: 'Voice Chat',
    voiceSub: 'Kausapin si Tsupher',
    voiceSoon: 'Text muna, boses malapit na',
    offlineTitle: '100% Offline',
    offlineBody:
      'Lahat ng info ay nasa telepono mo. Walang data na kailangan. Nasa phone mo lang ang lokasyon mo.',
  },
  offline: {
    title: 'Offline Mode',
    body: 'Gumagana ang Para! nang walang internet. Ito ang kasalukuyang lagay ng app sa phone mo.',
    rows: {
      sw: 'Offline na kopya ng app',
      pack: 'Route pack',
      ai: 'AI Assistant',
      inference: 'Huling sagot ng AI',
      crossOrigin: 'Request sa ibang server mula nang buksan',
    },
    checking: 'Tinitingnan…',
    swActive: 'Aktibo ang service worker',
    swInstalling: 'Ini-install pa. I-reload ang app.',
    swNone: 'Hindi naka-install',
    swNoneNote: 'Kailangan ng naka-build na bersyon. Hindi ito gumagana sa dev server.',
    packLoaded: (version: string, routes: number, fareAsOf: string) =>
      `Bersyon ${version} · ${routes} ruta · pamasahe as of ${fareAsOf}`,
    packFailed: 'Hindi mabuksan',
    aiInstalled: (model: string, size: string | null) => (size ? `${model} · ${size}` : model),
    aiAbsent: 'Hindi pa naka-install',
    aiDownloading: (percent: number) => `Dina-download: ${percent}%`,
    aiFailed: 'Hindi nagbukas ang model',
    noWebGpu: 'Walang WebGPU ang browser na ito',
    backendWebGpu: 'Backend: WebGPU, sa device mismo',
    rulesFallback: 'Simpleng pag-intindi (rules) ang gamit, walang AI model.',
    inference: (ms: number, tokensPerSecond: number | null) =>
      tokensPerSecond ? `${ms} ms · ${tokensPerSecond} tokens/s` : `${ms} ms`,
    noInference: 'Wala pa sa session na ito',
    notMeasurable: 'Hindi masukat sa browser na ito',
    crossOriginNote: 'Bilang ng browser mismo, kasama ang mga library.',
    crossOriginHosts: (hosts: string) => `Papunta sa: ${hosts}`,
    yes: 'Oo',
    no: 'Hindi',
    ok: 'Okay',
    bytesSent: 'Bytes sent',
    bytesNote: 'sukat ng app',
    bytesExplain:
      'Bilang ito ng app mismo. Ang tunay na patunay ay ang Network tab ng devtools.',
    private: 'Pribado at Ligtas',
    connection: 'Koneksyon ngayon',
  },
  stale: {
    short: 'Maaaring luma na ang pamasahe',
    long: (date: string, days: number) =>
      `Ang fare table ay as of ${date} (${days} araw na). Maaaring may bagong fare matrix. Tingnan ang nakapaskil sa sasakyan.`,
  },
  update: {
    title: 'May bagong bersyon ng Para!',
    action: 'I-update',
  },
  crash: {
    title: 'Naku, may nasira',
    body: 'Nagka-problema ang screen na ito. Ligtas ang data mo sa phone.',
    retry: 'Subukan ulit',
    home: 'Bumalik sa Home',
  },
  higit: {
    title: 'Higit Pa',
    modes: { label: 'Mga Mode', sub: 'Mas mura, iwas traffic, custom' },
    offline: { label: 'Offline Mode', sub: 'Tingnan kung ano ang gumagana nang walang internet' },
    settings: { label: 'Settings', sub: 'Wika at unit' },
    about: { label: 'About / Disclosure', sub: 'Mga library, model at pinagkunan ng data' },
    devRouter: { label: 'Router harness', sub: 'Dev only' },
    devComponents: { label: 'Components', sub: 'Dev only' },
    soon: 'Malapit na',
  },
  stub: {
    title: 'Ginagawa pa ito',
    paborito: 'Dito mase-save ang mga paborito mong ruta.',
  },
  chat: {
    subtitle: 'Gabay mo sa commute, sa phone mo lang',
    logLabel: 'Usapan ninyo ni Tsupher',
    placeholder: 'Type o magsalita…',
    send: 'Ipadala',
    thinking: 'Nag-iisip si Tsupher',
    wakingModel: 'Ginigising ang model…',
    found: 'Sige! Ito ang nahanap ko:',
    refined: 'Ayan, inayos ko na:',
    whatIf: 'Simulation lang ito, batay sa sinabi mong iwasan. Hindi ko alam ang totoong sarado o traffic.',
    askOrigin: 'Saan ka manggagaling?',
    askDestination: 'Saan ka papunta?',
    askBoth: 'Saan ka galing, at saan ka papunta?',
    pickOne: 'Alin dito ang ibig mong sabihin?',
    unsupported:
      'Pasensya na, ruta at pamasahe lang ang kaya kong sagutin. Subukan: sabihin kung saan ka galing at saan ka papunta.',
    reset: 'Sige, bagong biyahe tayo. Saan ka papunta?',
    error: 'May nagkamali sa akin. Pakisubukan ulit.',
    modelFailed:
      'Hindi nagbukas ang AI model, kaya simpleng pag-intindi muna ang gamit ko. Gumagana pa rin ang ruta at pamasahe.',
    quickCheaper: 'Mas mura',
    quickFewer: 'Mas kaunting sakay',
    quickAvoid: (tag: string) => `Iwas ${tag}`,
    pickOrigin: (name: string) => `galing ${name}`,
    pickDestination: (name: string) => `papunta sa ${name}`,
  },
  setup: {
    title: 'Gisingin si Tsupher',
    checking: 'Tinitingnan ang phone mo…',
    absentTitle: 'Tulog pa si Tsupher',
    absentBody:
      'I-download nang isang beses ang AI model para maintindihan ni Tsupher ang Taglish mo, kahit walang signal.',
    choose: 'Piliin ang model',
    wifi: 'Mag-WiFi muna. Malaki ang file at isang beses lang ito ida-download.',
    start: 'Gisingin si Tsupher',
    retry: 'Ituloy ang download',
    downloadingTitle: 'Ginigising si Tsupher…',
    keepUsing: 'Puwede mong gamitin ang app habang nagda-download. Gumagana pa rin ang Plan a Route.',
    errorTitle: 'Naputol',
    errorBody: 'Hindi natapos. Itutuloy mula sa na-download na.',
    errorQuota: 'Kulang ang storage ng phone para sa model. Magbura muna ng ibang file, o pumili ng mas maliit na model.',
    errorMemory: 'Kulang ang memory ng device para patakbuhin ang model na ito. Pumili ng mas maliit na model.',
    totalDownload: 'Kabuuang download: ang AI model lang. Kasama na sa app ang route pack.',
    readyTitle: 'Gising na si Tsupher!',
    readyBody: 'Nasa phone mo na ang model. Hindi na kailangan ng internet.',
    model: 'Model',
    license: 'Lisensya',
    modelSize: 'Laki sa phone',
    unknownSize: 'Hindi nasukat',
    remove: 'Burahin ang model',
    unsupportedTitle: 'Walang WebGPU ang browser na ito',
    unsupportedBody:
      'Hindi mapapatakbo ang AI model dito. Gumagana pa rin ang Plan a Route at ang simpleng pag-intindi ng tanong.',
    storage: (used: string, quota: string) => `Gamit na storage: ${used} sa ${quota}`,
    persisted: 'protektado sa pagbura',
    notPersisted: 'maaaring burahin ng browser kapag puno na',
    privacy:
      'Ang download lang ng model ang gumagamit ng internet. Hindi ipinapadala ang tanong, lokasyon o ruta mo.',
    homeTitle: 'Gisingin si Tsupher',
    homeBody: 'I-download ang AI model nang isang beses para mas maintindihan ka niya.',
  },
  units: {
    min: 'min',
    hour: 'oras',
    km: 'km',
  },
  mode: {
    jeepney: 'Jeepney',
    modern_jeepney: 'Modern Jeepney',
    uv: 'UV Express',
    bus: 'Bus',
    train: 'MRT/LRT',
    walk: 'Lakad',
  },
  pref: {
    cheapest: 'Mas mura',
    fastest: 'Mas mabilis',
    fewest_transfers: 'Pinakakaunting sakay',
    custom: 'Custom',
  },
  badge: {
    unverified: 'Hindi pa verified',
    simulated: 'Simulated',
    chosen: 'Pinili mo',
  },
  plan: {
    title: 'Plan a Route',
    modesLink: 'Mga Mode',
    loading: 'Binubuksan ang route pack…',
    packError: 'Hindi mabuksan ang route pack sa phone na ito.',
    origin: 'Saan ka galing?',
    destination: 'Saan ka papunta?',
    pickerPlaceholder: 'I-type ang lugar',
    pickerEmpty: 'Walang tugmang lugar sa route pack.',
    pickerAlias: 'kilala rin bilang',
    swap: 'Pagpalitin ang galing at papunta',
    preference: 'Ano ang mas mahalaga?',
    search: 'Hanap',
    searching: 'Hinahanap…',
    needBoth: 'Piliin muna ang pinanggalingan at pupuntahan.',
    activeAvoid: 'Iwas EDSA (simulated)',
    activeCustom: 'Custom Preference',
  },
  results: {
    title: 'Mga Ruta',
    found: (count: number) => (count === 1 ? '1 opsyon' : `${count} opsyon`),
    rides: (count: number) => `${count} sakay`,
    transfers: (count: number) => (count === 0 ? 'Walang lipat' : `${count} lipat`),
    walkOnly: 'Lakad lang',
    asOf: (date: string) => `Pamasahe as of ${date}`,
    noFare: 'Walang pamasahe',
    simulatedNote: 'Simulation ito batay sa iniwasan mo. Hindi alam ng app ang totoong sarado o traffic.',
    emptyTitle: 'Walang nahanap na ruta',
    back: 'Baguhin ang hanap',
  },
  reason: {
    unknown_origin: 'Hindi ko kilala ang pinanggalingan. Pumili mula sa listahan.',
    unknown_destination: 'Hindi ko kilala ang pupuntahan. Pumili mula sa listahan.',
    same_origin_destination: 'Pareho ang pinanggalingan at pupuntahan mo.',
    origin_avoided: 'Kasama sa iniiwasan mo ang pinanggalingan.',
    destination_avoided: 'Kasama sa iniiwasan mo ang pupuntahan.',
    no_path: 'Walang rutang nagdudugtong sa dalawang lugar na ito sa route pack.',
  },
  detail: {
    title: 'Detalye ng Ruta',
    favorite: 'I-save sa Paborito (malapit na)',
    board: 'Sakay',
    alight: 'Baba',
    fareButton: 'Paano nakuha ang pamasahe?',
    fareSheetTitle: 'Hati ng pamasahe',
    base: (km: number) => `Base (unang ${km} km)`,
    extra: (km: number, perKm: string) => `Dagdag: ${km} km × ${perKm}`,
    unrounded: 'Bago i-round',
    legFare: 'Pamasahe',
    total: 'Kabuuan',
    effective: 'Effective date',
    source: 'Pinagkunan',
    rounding: 'Rounding',
    fareDisclaimer:
      'Reference lang ito. Ang nakapaskil na fare matrix sa sasakyan ang masusunod.',
    notesTitle: 'Tandaan:',
    start: 'Simulan ang Ruta',
    seeMap: 'Tingnan sa mapa',
    none: 'Wala pang napiling ruta. Maghanap muna.',
  },
  trip: {
    title: 'Trip mode',
    body: 'Ginagawa pa ang Trip mode. Dito ka gagabayan ni Tsupher habang nasa biyahe.',
    back: 'Bumalik sa detalye',
  },
  modes: {
    title: 'Mga Mode',
    intro: 'Para sa mas magandang biyahe',
    cheap: { label: 'Mas Mura Mode', sub: 'Ipakita ang pinakamurang ruta.' },
    avoidEdsa: {
      label: 'Iwas Traffic / Iwas EDSA',
      sub: 'Maghanap ng alternatibong ruta na hindi dumadaan sa EDSA.',
      note: 'Simulated: ikaw ang nagsabing iwasan ito. Hindi alam ng app ang totoong traffic.',
    },
    custom: {
      label: 'Custom Preference',
      sub: 'Ikaw ang magtitimbang ng pamasahe, oras at dami ng lipat.',
      fare: 'Pamasahe',
      minutes: 'Oras',
      transfers: 'Dami ng lipat',
      scale: (value: number) => `${value} sa 10`,
    },
    on: 'Naka-on',
    off: 'Naka-off',
    settings: 'Mga Setting',
    language: { label: 'Wika', value: 'Taglish (Default)' },
    unit: { label: 'Unit', value: 'Piso at minuto' },
    done: 'Okay',
  },
  map: {
    title: 'Mapa ng Ruta',
    schematic: 'Schematic lang ito mula sa route pack. Hindi ito totoong mapa ng kalsada.',
    noRoute: 'Wala pang napiling ruta. Ipinapakita ang buong network.',
    planFirst: 'Mag-plan ng ruta',
    zoomIn: 'Palakihin',
    zoomOut: 'Paliitin',
    reset: 'Ibalik ang view',
    origin: 'Simula',
    destination: 'Dulo',
    transfer: 'Lipatan',
    legend: 'Legend',
    describe: (from: string, to: string, legs: number) =>
      `Schematic na mapa mula ${from} hanggang ${to}, ${legs} bahagi.`,
    describeNetwork: 'Schematic na mapa ng buong route pack.',
  },
  about: {
    title: 'About',
    intro:
      'Ang Para! ay offline na katulong sa commute. Walang account, walang analytics, walang lumalabas sa device na ito.',
    libraries: 'Mga library',
    models: 'Mga model',
    modelsNote:
      'Hindi kasama sa app ang mga model. Isa lang ang dina-download, kapag pinili mo sa Gisingin si Tsupher, at sa device lang ito tumatakbo (WebLLM, WebGPU).',
    modelInstalled: 'Naka-install',
    data: 'Pinagkunan ng data',
    dataLoading: 'Binabasa ang local database…',
    dataNote: 'Synthetic na test network lang. Walang totoong ruta, terminal o pamasahe.',
    packVersion: (id: string, version: string) => `Route pack: ${id}, bersyon ${version}`,
    fareAsOf: (date: string) => `Pamasahe as of ${date}`,
    fonts: 'Mga font',
    art: 'Art',
    artNote:
      'Ang mga sprite ni Tsupher ay awtomatikong ginupit mula sa reference sheet (draft). Placeholder pa ang wordmark.',
  },
  tsupher: {
    hero: 'Si Tsupher, ang jeepney na gabay mo',
    happy: 'Si Tsupher, nakangiti',
    thinking: 'Si Tsupher, nag-iisip',
    map: 'Si Tsupher, nagbabasa ng mapa',
    'thumbs-up': 'Si Tsupher, naka-thumbs up',
    confused: 'Si Tsupher, nalilito',
    sad: 'Si Tsupher, malungkot',
    sign: 'Si Tsupher, may hawak na karatula',
    driving: 'Si Tsupher, umaandar',
    luggage: 'Si Tsupher, may dalang maleta',
    jumping: 'Si Tsupher, tumatalon sa tuwa',
    love: 'Si Tsupher, kinikilig',
    excited: 'Si Tsupher, excited',
  },
} as const
